---
mac_ssh_config_marker: "# K8s Homelab"

# Hosts to add to Mac /etc/hosts (only jump and vault needed from Mac)
mac_hosts_entries: |
  # K8s Homelab VMs
  {{ network_prefix }}.11  vault
  {{ network_prefix }}.12  jump
  # End K8s Homelab

jump_host_ip: "{{ network_prefix }}.12"
ssh_key_private: "{{ ansible_env.HOME }}/.ssh/k8slab.key"
